#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"




while true; do

echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m                        MONITOR                      \033[0m"
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"

echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m   Usuario                          Conectado/Limite \033[0m"
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
        for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9] |sort`; do
	if [ -f /etc/VpsPackdir/limite/$usur ]
	then
	if [[ $(cat /etc/VpsPackdir/limite/$usur) == "" ]]
	then
	limite=null
	else
	limite=$(cat /etc/VpsPackdir/limite/$usur)
	fi
	else
	limite=null
	fi
	usurnum="$(ps -u $usur |grep sshd |wc -l)/$limite"
        echo -e "\033[1;33m    $(printf '%-41s%s' $usur $usurnum) \033[0m"
        echo -e "\033[1;37m -----------------------------------------------------\033[0m"
        done
sleep 6s
clear
done
